#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

REPO_SLUG="cylim/supreme-dollop"
RELEASE_ENVIRONMENT="release-preview"
PRODUCTION_ENVIRONMENT="production-check"

github_ready() {
  command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1
}

environment_exists() {
  gh api "repos/$REPO_SLUG/environments/$1" >/dev/null 2>&1
}

ensure_environment() {
  local environment="$1"
  if ! github_ready; then
    SKIPPED+=("GitHub environment $environment")
    warn "gh is not authenticated; create $environment manually."
    return
  fi
  if environment_exists "$environment"; then
    note "GitHub environment $environment already exists."
    return
  fi
  if confirm "Create the GitHub environment $environment now?"; then
    gh api --method PUT "repos/$REPO_SLUG/environments/$environment" >/dev/null
    printf '  %s✓ created%s GitHub environment %s\n' "$GREEN" "$RESET" "$environment"
  else
    SKIPPED+=("GitHub environment $environment")
  fi
}

environment_secret_exists() {
  local environment="$1" name="$2"
  gh secret list --repo "$REPO_SLUG" --env "$environment" \
    --json name --jq ".[] | select(.name == \"$name\") | .name" 2>/dev/null \
    | grep -qx "$name"
}

set_environment_secret() {
  local environment="$1" name="$2" value="$3"
  if github_ready && printf '%s' "$value" \
    | gh secret set "$name" --repo "$REPO_SLUG" --env "$environment" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$environment/$name")
    printf '  %s✓ set%s %s secret %s\n' "$GREEN" "$RESET" "$environment" "$name"
    return
  fi
  SKIPPED+=("$environment secret $name")
  warn "could not set $environment secret $name"
}

capture_environment_secret() {
  local environment="$1" name="$2" prompt="$3" value=""
  if github_ready && environment_secret_exists "$environment" "$name"; then
    note "$environment already has secret $name."
    if ! confirm "Replace $name?"; then
      return
    fi
  fi
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -rs value || true
  printf '\n'
  if [[ -z "$value" ]]; then
    SKIPPED+=("$environment secret $name")
    warn "$name was empty; leaving it unchanged."
    return
  fi
  set_environment_secret "$environment" "$name" "$value"
}

environment_variable_value() {
  local environment="$1" name="$2"
  gh variable get "$name" --repo "$REPO_SLUG" --env "$environment" \
    --json value --jq .value 2>/dev/null
}

set_environment_variable() {
  local environment="$1" name="$2" value="$3"
  if github_ready && gh variable set "$name" --repo "$REPO_SLUG" \
    --env "$environment" --body "$value" >/dev/null 2>&1; then
    printf '  %s✓ set%s %s variable %s\n' "$GREEN" "$RESET" "$environment" "$name"
    return
  fi
  SKIPPED+=("$environment variable $name")
  warn "could not set $environment variable $name"
}

capture_environment_variable() {
  local environment="$1" name="$2" prompt="$3" fallback="${4:-}" current="" value=""
  if github_ready; then
    current=$(environment_variable_value "$environment" "$name" || true)
  fi
  [[ -z "$current" ]] && current="$fallback"
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps %s]%s ' \
      "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r value || true
  [[ -z "$value" ]] && value="$current"
  if [[ -z "$value" ]]; then
    SKIPPED+=("$environment variable $name")
    warn "$name was empty; leaving it unchanged."
    return
  fi
  set_environment_variable "$environment" "$name" "$value"
}

check_environment_setting() {
  local kind="$1" environment="$2" name="$3"
  if [[ "$kind" == "secret" ]]; then
    if ! environment_secret_exists "$environment" "$name"; then
      SKIPPED+=("$environment secret $name")
      warn "missing $environment secret $name"
    fi
  elif ! environment_variable_value "$environment" "$name" >/dev/null; then
    SKIPPED+=("$environment variable $name")
    warn "missing $environment variable $name"
  fi
}

banner "Comprehensive testing setup"

stage "GitHub preflight"
say "This wizard configures CI for $REPO_SLUG; it never writes secrets to disk."
if github_ready; then
  DETECTED_REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)
  note "Authenticated GitHub account: $(gh api user --jq .login)"
  note "Repository detected from this checkout: ${DETECTED_REPO:-unknown}"
  if [[ -n "$DETECTED_REPO" && "$DETECTED_REPO" != "$REPO_SLUG" ]]; then
    warn "Expected $REPO_SLUG but detected $DETECTED_REPO. Stop and inspect before continuing."
    pause "Press Enter to continue anyway, or Ctrl-C to stop."
  fi
else
  warn "GitHub CLI is missing or unauthenticated."
  step "Install gh, then run: gh auth login"
  SKIPPED+=("GitHub authentication")
  pause "Authenticate GitHub before continuing if you want automatic writes."
fi
for tool in node npm npx; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    SKIPPED+=("required command $tool")
    warn "$tool is not installed."
  fi
done

stage "GitHub environments"
say "The workflows isolate release credentials from production monitoring credentials."
ensure_environment "$RELEASE_ENVIRONMENT"
ensure_environment "$PRODUCTION_ENVIRONMENT"
open_url "https://github.com/$REPO_SLUG/settings/environments"
step "Open release-preview. Restrict deployment branches to main and add a reviewer if your plan supports it."
step "Open production-check. Restrict it to main and require a reviewer for credential changes."
note "Environment secrets are exposed only after the environment's protection rules pass."
pause "Finish the protection rules, then press Enter."

stage "Convex preview deployment"
say "The release gate creates a fresh preview, seeds it, tests it, and deletes it."
open_url "https://dashboard.convex.dev"
step "Open the supreme-dollop project, then Project Settings → Deploy Keys."
step "Generate a Preview Deploy Key and copy it. Do not use a production deploy key."
capture_environment_secret "$RELEASE_ENVIRONMENT" CONVEX_PREVIEW_DEPLOY_KEY \
  "Paste the Convex preview deploy key:"
step "In Project Settings → Default Environment Variables, select Preview defaults."
step "Verify AUTH_PRIVATE_KEY and AUTH_JWKS are present. Generate preview-specific auth keys if absent."
warn "The first Convex deploy cannot succeed unless both required auth values already exist as preview defaults."
pause "Confirm the two Convex preview auth defaults are configured."

stage "Convex preview cleanup"
say "A management token lets the always-run cleanup step delete the disposable preview."
open_url "https://dashboard.convex.dev"
step "Open your profile or team settings, then create a management API access token."
step "Use a dedicated CI token with access to this Convex project and copy it now."
capture_environment_secret "$RELEASE_ENVIRONMENT" CONVEX_MANAGEMENT_TOKEN \
  "Paste the Convex management token:"
note "The release workflow uses this only after testing, including on failures."

stage "Google Calendar integration"
say "The integration check exchanges a refresh token and calls Calendar freeBusy."
open_url "https://console.cloud.google.com/apis/credentials"
step "Enable Google Calendar API and configure an OAuth consent screen for the test account."
step "Create or open a Web application OAuth client."
step "Add https://developers.google.com/oauthplayground as an authorized redirect URI."
step "Copy the client ID and client secret into the prompts below."
capture_environment_secret "$RELEASE_ENVIRONMENT" AUTH_GOOGLE_CLIENT_ID \
  "Paste the Google OAuth client ID:"
capture_environment_secret "$RELEASE_ENVIRONMENT" AUTH_GOOGLE_CLIENT_SECRET \
  "Paste the Google OAuth client secret:"
open_url "https://developers.google.com/oauthplayground"
step "Open OAuth Playground settings, enable 'Use your own OAuth credentials', and enter that client."
step "Set access type to Offline and force the consent screen."
step "Authorize only https://www.googleapis.com/auth/calendar.freebusy with the dedicated test account."
step "Exchange the authorization code for tokens, then copy the refresh token."
capture_environment_secret "$RELEASE_ENVIRONMENT" GOOGLE_CALENDAR_TEST_REFRESH_TOKEN \
  "Paste the Google Calendar refresh token:"
capture_environment_variable "$RELEASE_ENVIRONMENT" GOOGLE_CALENDAR_TEST_ID \
  "Calendar ID for the free/busy check:" "primary"
open_url "https://dashboard.convex.dev"
step "Return to this project's Preview default environment variables."
step "Set AUTH_GOOGLE_CLIENT_ID and AUTH_GOOGLE_CLIENT_SECRET to the same OAuth client values."
warn "Google OAuth apps left in Testing status commonly issue refresh tokens that expire after seven days."
pause "Finish the Convex preview defaults, then press Enter."

stage "AgentMail integration"
say "The real mail check sends a unique message and confirms it reaches a second inbox."
open_url "https://console.agentmail.to"
step "Create or select a dedicated test organization or pod."
step "Create two inboxes: one sender and one recipient."
step "Create a dedicated API key that can send from the first inbox and read the second."
step "Copy the API key immediately; AgentMail displays the full key only once."
capture_environment_secret "$RELEASE_ENVIRONMENT" AGENTMAIL_API_KEY \
  "Paste the AgentMail API key:"
capture_environment_variable "$RELEASE_ENVIRONMENT" AGENTMAIL_INBOX_ID \
  "Sender inbox ID:"
capture_environment_variable "$RELEASE_ENVIRONMENT" AGENTMAIL_TEST_RECIPIENT \
  "Recipient inbox email address:"
capture_environment_variable "$RELEASE_ENVIRONMENT" AGENTMAIL_TEST_RECIPIENT_INBOX_ID \
  "Recipient inbox ID:"

stage "Browser-test identities"
say "Use dedicated synthetic identities; never reuse a personal or production password."
step "Choose distinct host and participant addresses controlled by your test setup."
step "Choose long, unique passwords. Input is hidden and written only to GitHub."
capture_environment_secret "$RELEASE_ENVIRONMENT" E2E_HOST_EMAIL \
  "Host test email:"
capture_environment_secret "$RELEASE_ENVIRONMENT" E2E_HOST_PASSWORD \
  "Host test password:"
capture_environment_secret "$RELEASE_ENVIRONMENT" E2E_GUEST_EMAIL \
  "Participant test email:"
capture_environment_secret "$RELEASE_ENVIRONMENT" E2E_GUEST_PASSWORD \
  "Participant test password:"
note "The disposable preview allowlists these identities before browser tests run."

stage "Stable advisory target"
say "Firefox and WebKit advisory tests need a stable staging app; the release preview is deleted after each run."
step "Deploy or open a non-production staging instance with E2E password auth enabled only for the synthetic identities."
step "Seed one public schedule and one public decision whose URLs remain stable."
capture_environment_variable "$RELEASE_ENVIRONMENT" E2E_BASE_URL \
  "Stable staging base URL, including https://:"
capture_environment_variable "$RELEASE_ENVIRONMENT" E2E_PUBLIC_SCHEDULE_URL \
  "Stable public schedule URL:"
capture_environment_variable "$RELEASE_ENVIRONMENT" E2E_PUBLIC_DECISION_URL \
  "Stable public decision URL:"
warn "Do not paste disposable preview URLs here."

stage "Production read-only checks"
say "Production monitoring signs in, then blocks Convex mutations while loading two fixtures."
warn "Only continue if production has an allowlisted synthetic account and intentionally exposes /e2e-login to it."
capture_environment_secret "$PRODUCTION_ENVIRONMENT" E2E_HOST_EMAIL \
  "Production synthetic account email:"
capture_environment_secret "$PRODUCTION_ENVIRONMENT" E2E_HOST_PASSWORD \
  "Production synthetic account password:"
capture_environment_variable "$PRODUCTION_ENVIRONMENT" E2E_BASE_URL \
  "Production base URL, including https://:"
capture_environment_variable "$PRODUCTION_ENVIRONMENT" E2E_PUBLIC_SCHEDULE_URL \
  "Production read-only schedule fixture URL:"
capture_environment_variable "$PRODUCTION_ENVIRONMENT" E2E_PUBLIC_DECISION_URL \
  "Production read-only decision fixture URL:"
note "Use durable, non-sensitive fixtures that monitoring may read every 15 minutes."

stage "Verify and optionally run"
say "Checking names only; secret values are never read back or printed."
if github_ready; then
  for name in \
    CONVEX_PREVIEW_DEPLOY_KEY CONVEX_MANAGEMENT_TOKEN \
    E2E_HOST_EMAIL E2E_HOST_PASSWORD E2E_GUEST_EMAIL E2E_GUEST_PASSWORD \
    AGENTMAIL_API_KEY AUTH_GOOGLE_CLIENT_ID AUTH_GOOGLE_CLIENT_SECRET \
    GOOGLE_CALENDAR_TEST_REFRESH_TOKEN; do
    check_environment_setting secret "$RELEASE_ENVIRONMENT" "$name"
  done
  for name in \
    AGENTMAIL_INBOX_ID AGENTMAIL_TEST_RECIPIENT \
    AGENTMAIL_TEST_RECIPIENT_INBOX_ID GOOGLE_CALENDAR_TEST_ID \
    E2E_BASE_URL E2E_PUBLIC_SCHEDULE_URL E2E_PUBLIC_DECISION_URL; do
    check_environment_setting variable "$RELEASE_ENVIRONMENT" "$name"
  done
  for name in E2E_HOST_EMAIL E2E_HOST_PASSWORD; do
    check_environment_setting secret "$PRODUCTION_ENVIRONMENT" "$name"
  done
  for name in E2E_BASE_URL E2E_PUBLIC_SCHEDULE_URL E2E_PUBLIC_DECISION_URL; do
    check_environment_setting variable "$PRODUCTION_ENVIRONMENT" "$name"
  done

  if confirm "Trigger the advisory Firefox/WebKit and real-integration workflow now?"; then
    gh workflow run advisory-tests.yml --repo "$REPO_SLUG"
    note "Triggered Advisory tests. Watch it under GitHub Actions."
  fi
  if confirm "Trigger the disposable release gate now?"; then
    gh workflow run release-gate.yml --repo "$REPO_SLUG"
    note "Triggered Release gate. It creates and later deletes a Convex preview."
  fi
  if confirm "Trigger the production read-only check now?"; then
    gh workflow run production-check.yml --repo "$REPO_SLUG"
    note "Triggered Production read-only check."
  fi
else
  SKIPPED+=("configuration validation and workflow triggers")
  warn "gh is not ready, so validation and workflow triggers were skipped."
fi

finish
